name: Build and Push sebos Container

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase repository owner
        id: repo_owner
        run: echo "owner=${OWNER,,}" >> $GITHUB_OUTPUT
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: distro.containerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ steps.repo_owner.outputs.owner }}/sebos:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  cleanup:
    name: Cleanup Old Container Versions
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: cleanup-images
    permissions:
      packages: write
    steps:
      - name: Cleanup Old GHCR Images
        uses: step-security/ghcr-cleanup-action@v1
        with:
          packages: 'sebos'
          keep-n-tagged: 3
          token: ${{ secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}
